import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiDownload, FiEye, FiMail, FiMapPin, FiSearch, FiUserCheck, FiPhone, FiCreditCard } from "react-icons/fi";
import api from "../../services/api";

export default function CandidateSearch() {
  const [filters,setFilters]=useState({q:"",location:"",skill:""}); const [candidates,setCandidates]=useState([]); const [access,setAccess]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [selected,setSelected]=useState(null); const [busy,setBusy]=useState(""); const [contact,setContact]=useState(null);
  const load=async()=>{try{setLoading(true);setError("");const r=await api.get("/recruiter/candidates",{params:filters});setCandidates(r.data.candidates||[]);setAccess(r.data.cvAccess)}catch(e){setError(e.response?.data?.message||"Unable to search candidates.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const preview=async(id)=>{try{setBusy(id);const r=await api.get(`/recruiter/candidates/${id}`);setSelected(r.data)}catch(e){setError(e.response?.data?.message||"Unable to load candidate.")}finally{setBusy("")}};
  const unlock=async(id)=>{if(!confirm("Unlock this candidate CV? One free monthly CV allowance or one paid credit will be used."))return;try{setBusy(`u:${id}`);const r=await api.post(`/recruiter/candidates/${id}/unlock`);setSelected(r.data);setAccess(r.data.cvAccess);await load()}catch(e){setError(e.response?.data?.message||"Unable to unlock candidate CV.")}finally{setBusy("")}};
  const download=async(id)=>{try{setBusy(`d:${id}`);const r=await api.get(`/recruiter/candidates/${id}/resume`,{responseType:"blob"});const url=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=url;a.download="candidate-resume";a.click();URL.revokeObjectURL(url);await load()}catch(e){setError(e.response?.data?.message||"Unable to download CV.")}finally{setBusy("")}};
  const contactCandidate=async(id)=>{try{const r=await api.post(`/recruiter/candidates/${id}/contact`);setContact(r.data.candidate)}catch(e){setError(e.response?.data?.message||"Unable to load contact details.")}};
  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-7xl px-6 py-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-blue-600">Recruiter</p><h1 className="mt-1 text-3xl font-bold">Search Candidates</h1><p className="mt-2 text-slate-500">Browse privacy-protected candidate profiles. Basic information is visible before CV access is purchased.</p></div><Link to="/recruiter/packages" className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-semibold"><FiCreditCard/> Buy CV Credits</Link></div>
    {access&&<div className="mt-6 grid gap-4 md:grid-cols-3"><Balance label="Free CVs remaining this month" value={access.freeRemaining}/><Balance label="Paid CV credits" value={access.paidCredits}/><Balance label="Cost per new candidate" value={`${access.creditCost} credit`}/></div>}
    {access && access.freeRemaining === 0 && access.paidCredits === 0 && <div className="mt-5 flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-bold text-amber-900">Your free CV allowance is used</p><p className="mt-1 text-sm text-amber-700">Purchase a CV credit package to unlock additional candidate resumes.</p></div><Link to="/recruiter/packages" className="rounded-xl bg-blue-600 px-5 py-3 text-center text-sm font-semibold text-white">View CV Packages</Link></div>}
    <div className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[2fr_1fr_1fr_auto]"><input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder="Name, headline or skill" className="rounded-xl border px-4 py-3"/><input value={filters.location} onChange={e=>setFilters({...filters,location:e.target.value})} placeholder="Location" className="rounded-xl border px-4 py-3"/><input value={filters.skill} onChange={e=>setFilters({...filters,skill:e.target.value})} placeholder="Skill" className="rounded-xl border px-4 py-3"/><button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><FiSearch/> Search</button></div></div>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{loading?<div className="col-span-full rounded-2xl border bg-white p-10 text-center">Searching...</div>:candidates.map(c=><div key={c._id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-full bg-blue-50 font-bold text-blue-600">{c.profileImage?<img src={c.profileImage} className="h-full w-full object-cover"/>:<FiUserCheck/>}</div><div className="min-w-0"><h2 className="font-bold">{c.name}</h2><p className="text-sm text-slate-500">{c.headline||"Candidate"}</p>{c.location&&<p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><FiMapPin/>{c.location}</p>}</div></div><div className="mt-4 flex flex-wrap gap-2">{(c.skills||[]).slice(0,6).map(s=><span key={s} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{s}</span>)}</div><p className="mt-4 text-sm text-slate-500">{c.experience?c.experience.slice(0,130):"Professional experience available after CV access."}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>preview(c._id)} className="rounded-lg border px-3 py-2 text-sm font-semibold">{busy===c._id?"Loading...":"View Profile"}</button>{c.cvUnlocked?<><button onClick={()=>download(c._id)} className="inline-flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><FiDownload/>{busy===`d:${c._id}`?"Downloading":"Download CV"}</button><button onClick={()=>contactCandidate(c._id)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold"><FiMail/>Contact</button></>:<button onClick={()=>unlock(c._id)} className="inline-flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><FiEye/>{busy===`u:${c._id}`?"Unlocking":"Unlock CV"}</button>}</div></div>)}</div>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-5" onClick={()=>{setSelected(null);setContact(null)}}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-blue-600">Candidate Profile</p><h2 className="mt-1 text-2xl font-bold">{selected.candidate?.name}</h2></div><button onClick={()=>setSelected(null)} className="text-slate-400">×</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Info label="Headline" value={selected.candidate?.headline}/><Info label="Location" value={selected.candidate?.location}/><Info label="Skills" value={(selected.candidate?.skills||[]).join(", ")}/><Info label="Education" value={selected.candidate?.education}/></div>{selected.unlocked?<><div className="mt-6 rounded-xl bg-green-50 p-4 text-sm text-green-700">CV unlocked. Your balance has been charged only once for this candidate.</div><div className="mt-5 grid gap-4 md:grid-cols-2"><Info label="Email" value={selected.candidate?.email}/><Info label="Phone" value={selected.candidate?.phone}/><Info label="LinkedIn" value={selected.candidate?.linkedin}/><Info label="Portfolio" value={selected.candidate?.portfolio}/></div><div className="mt-5 flex gap-2"><button onClick={()=>download(selected.candidate._id)} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Download CV</button><button onClick={()=>contactCandidate(selected.candidate._id)} className="rounded-xl border px-5 py-3 font-semibold">Contact Candidate</button></div>{contact&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><b>Contact:</b> {contact.email||"—"} · {contact.phone||"—"}</div>}</>:<div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-800">CV is private</p><p className="mt-1 text-sm text-amber-700">Unlocking the CV reveals protected contact and resume information and consumes one available CV unit.</p><button onClick={()=>unlock(selected.candidate._id)} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Unlock CV</button></div>}</div></div>}
  </main></div>
}
function Balance({label,value}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>} function Info({label,value}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-700">{value||"Not added"}</p></div>}
