import { useEffect, useState } from "react";
import AdminManagementShell from "./AdminManagementShell";
import api from "../../services/api";

const empty = { name: "", description: "", credits: 10, price: 499, currency: "INR", active: true, sortOrder: 0 };
export default function Packages() {
  const [packages, setPackages] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); const r = await api.get("/admin/packages"); setPackages(r.data.packages || []); } catch(e){setError(e.response?.data?.message || "Unable to load packages.");} finally{setLoading(false);} };
  useEffect(()=>{load()},[]);
  const save=async(e)=>{e.preventDefault();try{if(editing) await api.patch(`/admin/packages/${editing}`,form);else await api.post("/admin/packages",form);setForm(empty);setEditing(null);await load()}catch(e){setError(e.response?.data?.message||"Unable to save package.")}};
  const edit=(p)=>{setEditing(p._id);setForm({name:p.name,description:p.description||"",credits:p.credits,price:p.price,currency:p.currency||"INR",active:p.active,sortOrder:p.sortOrder||0})};
  const remove=async(id)=>{if(!confirm("Delete this package?"))return;try{await api.delete(`/admin/packages/${id}`);await load()}catch(e){setError(e.response?.data?.message||"Unable to delete package.")}};
  return <AdminManagementShell title="CV Package Configuration" description="Create, edit, activate and remove recruiter CV credit packages." onRefresh={load}><div className="grid gap-6 lg:grid-cols-[360px_1fr]">{error&&<div className="lg:col-span-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">{editing?"Edit package":"New package"}</h2><div className="mt-5 space-y-4">{[["name","Name","text"],["description","Description","text"],["credits","Credits","number"],["price","Price (₹)","number"],["sortOrder","Sort order","number"]].map(([key,label,type])=><label key={key} className="block text-sm font-medium text-slate-700">{label}<input type={type} value={form[key]} onChange={e=>setForm({...form,[key]:type==="number"?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-blue-500" required={key==="name"||key==="credits"||key==="price"}/></label>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><div className="flex gap-2"><button className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">{editing?"Update":"Create"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button>}</div></div></form><div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="border-b p-5 font-semibold">Packages</div>{loading?<p className="p-6 text-slate-500">Loading...</p>:<div className="divide-y">{packages.map(p=><div key={p._id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div><h3 className="font-bold">{p.name} <span className="ml-2 text-sm font-normal text-slate-500">{p.credits} credits · ₹{p.price}</span></h3><p className="mt-1 text-sm text-slate-500">{p.description||"No description"}</p></div><div className="flex gap-2"><button onClick={()=>edit(p)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Edit</button><button onClick={()=>remove(p._id)} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600">Delete</button></div></div>)}</div>}</div></div></AdminManagementShell>
}
